
from fastapi import APIRouter, UploadFile, File, HTTPException
from pathlib import Path
import tempfile
import os
from ai.transcriber import Transcriber

from audio.processor import preprocess_audio
from ai.voice_detector import PretrainedDetector


router = APIRouter()

# Model ek baar load hoga
# Har request par model reload nahi hoga
voice_detector = PretrainedDetector()
transcriber = Transcriber()

@router.post("/analyze")
async def analyze_audio(file: UploadFile = File(...)):

    # -----------------------------
    # 1. Validate file
    # -----------------------------
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="No file provided"
        )

    suffix = Path(file.filename).suffix.lower()

    temp_input = None

    try:

        # -----------------------------
        # 2. Save uploaded file temporarily
        # -----------------------------
        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=suffix if suffix != ".wav" else ".input.wav"
        ) as temp:

            temp_input = temp.name

            content = await file.read()
            temp.write(content)

        # -----------------------------
        # 3. Audio preprocessing
        #    Existing processor
        # -----------------------------
        processed = preprocess_audio(temp_input)

        waveform = processed["waveform"]
        sample_rate = processed["sample_rate"]
        duration = processed["duration"]

        # -----------------------------
        # 4. AASIST voice detection
        # -----------------------------
        spoof_probability = voice_detector.predict(
            waveform,
            sample_rate
        )

        transcription = transcriber.transcribe(
    processed["wav_path"]
 )

        real_probability = 1.0 - spoof_probability

        # -----------------------------
        # 5. Convert probability to risk
        # -----------------------------
        voice_risk = round(
            spoof_probability * 100,
            2
        )

        # -----------------------------
        # 6. Risk classification
        # -----------------------------
        if voice_risk < 40:

            risk_level = "GREEN"
            action = "ALLOW"

        elif voice_risk < 70:

            risk_level = "AMBER"
            action = "STEP_UP_AUTHENTICATION"

        else:

            risk_level = "RED"
            action = "HOLD_TRANSACTION_AND_ALERT"

        # -----------------------------
        # 7. Response
        # -----------------------------
        return {
            "filename": file.filename,

            "duration": round(
                duration,
                3
            ),

            "sample_rate": sample_rate,

            "spoof_probability": round(
                spoof_probability,
                4
            ),

            "real_probability": round(
                real_probability,
                4
            ),

            "voice_risk": voice_risk,

            "risk_level": risk_level,

            "action": action,

            "transcription": transcription
        }

    # -----------------------------
    # 8. Error handling
    # -----------------------------
    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    # -----------------------------
    # 9. Cleanup temporary files
    # -----------------------------
    finally:

        # Remove uploaded temporary file
        if temp_input and os.path.exists(temp_input):
            os.remove(temp_input)

        # Remove WAV generated by processor
        if temp_input:

            wav_path = str(
                Path(temp_input).with_suffix(".wav")
            )

            if os.path.exists(wav_path):
                os.remove(wav_path)

 